# This playbox updates a fedora 22 instance and installs EAP 6.4

- name: Update Fedora 22 Instance
  hosts: digital_ocean
  user: root

  tasks:
    - include: tasks/update-fedora.yml

- name: Install BPM 6.1.2 on EAP 6.4.2
  hosts: digital_ocean
  user: root

  tasks:
    - include: tasks/do-install-eap-6.4.yml
    - include: tasks/do-install-bpm-6.1.2.yml


  # http://download.eng.bos.redhat.com/brewroot/repos/jb-ip-6.1-build/latest/maven/org/jboss/ip/jboss-bpmsuite/6.1.2.GA-redhat-3/jboss-bpmsuite-6.1.2.GA-redhat-3-deployable-eap6.x.zip
