- name: Update Fedora 22 Instance and Install EAP with Jenkins
  hosts: jenkins_sonatype_test  
  remote_user: fedora
  vars:
    eap_filename: jboss-eap-6.4.3-full-build.zip
    nexus_filename: nexus-iq-server-1.17.0-02-bundle.zip
    sonatype_plugin_filename: sonatype-clm-ci-2.14.2-01.hpi
    user_name: fedora

  tasks:
    - include: tasks/update-fedora.yml
    - include: tasks/public-install-eap-6.4.yml
    - include: tasks/eap-6.4-configuration.yml
    - include: tasks/configure-maven.yml
    - include: tasks/install-jenkins.yml
    - include: tasks/install-nexus.yml
    - include: tasks/start-nexus.yml
    - include: tasks/start-eap.yml
    - include: tasks/install-sonatype-plugin.yml
    - include: tasks/install-jenkins-plugins.yml
    - include: tasks/jenkins-configuration.yml
    - include: tasks/stop-eap.yml
    - include: tasks/start-eap.yml


#######################################################
# Test Machine:jpmc_test (10.3.10.0)
# Host names found in ansible/hosts

# Command to run: ansible-playbook -i hosts fedora22-nexus.yml

# Manual Downloads
# Download into ansible/files directory

# JBoss EAP
# http://download.devel.redhat.com/released/JBEAP-6/6.4.3/jboss-eap-6.4.3-full-build.zip

# Nexus
# http://download.sonatype.com/clm/server/nexus-iq-server-1.17.0-02-bundle.zip

# Nexus .hpi Jenkins Plugin
# http://download.sonatype.com/clm/ci/sonatype-clm-ci-2.14.2-01.hpi


