# This playbox updates a fedora 22 instance and installs EAP 6.4

- name: Update Fedora 22 Instance
  hosts: os1_private
  user: fedora

  tasks:
#    - include: tasks/update-fedora.yml

- name: Install BPM {{bpm_version}} on EAP {{eap_version}}
  hosts: os1_private
  user: fedora

  environment:
   INVENTORY_HOSTNAME: "{{ inventory_hostname }}"

  tasks:
    - include: tasks/private-install-eap.yml
    - include: tasks/private-install-bpm.yml
    - include: tasks/eap-configuration.yml
    - include: tasks/maven-configuration.yml
    - include: tasks/start-eap.yml

  # http://download.eng.bos.redhat.com/brewroot/repos/jb-ip-6.1-build/latest/maven/org/jboss/ip/jboss-bpmsuite/6.1.2.GA-redhat-3/jboss-bpmsuite-6.1.2.GA-redhat-3-deployable-eap6.x.zip
