
- name: Copy EAP Standalone Startup Configuration
  copy: src=files/standalone.conf dest=~/jboss-eap-6.4/bin/standalone.conf owner=fedora group=fedora

- name: Copy EAP Standalone User Configuration
  copy: src=files/{{ item }} dest=~/jboss-eap-6.4/standalone/configuration/{{ item }} owner=fedora group=fedora
  with_items:
  - "application-roles.properties"  
  - "application-users.properties"  # jboss - bpmsuite1!
  - "mgmt-groups.properties"
  - "mgmt-users.properties"
