# Configure EAP 
# Bind EAP to public facing ports: 8080

- name: Copy EAP Standalone Startup Configuration
  copy: src=files/standalone.conf dest=/home/{{user_name}}/jboss-eap-6.4/bin/standalone.conf owner=fedora group=fedora

- name: Copy EAP Standalone User Configuration
  copy: src=files/{{ item }} dest=/home/{{user_name}}/jboss-eap-6.4/standalone/configuration/{{ item }} owner=fedora group=fedora
  with_items:
  - "application-roles.properties"  
  - "application-users.properties"
  - "mgmt-groups.properties"
  - "mgmt-users.properties"
