# Installs a Nexus server

# Instructions: Manually download Nexus into /files directory

# Nexus
# http://download.sonatype.com/clm/server/nexus-iq-server-1.17.0-02-bundle.zip?elqid=d68c23a6-5c1a-4919-bfce-09e93169cb4a

- name: Create Download dir
  file: path=/home/{{user_name}}/downloads state=directory mode=0755

- name: Create Nexus home dir
  file: path=/home/{{user_name}}/nexus state=directory mode=0755

- name: Copy Nexus
  copy: src=files/{{nexus_filename}} dest=/home/{{user_name}}/downloads/{{nexus_filename}} owner={{user_name}} group={{user_name}}

- name: Extract Nexus
  unarchive: src=/home/{{user_name}}/downloads/{{nexus_filename}} dest=/home/{{user_name}}/nexus copy=no owner={{user_name}} group={{user_name}}
