# Install Jenkins Plugins
- name: Check that .jenkins directory has been created
  wait_for: path=/home/{{user_name}}/.jenkins/plugins

- name: Install Git Plugin w/ Dependencies
  get_url: url={{ item }} dest=/home/{{user_name}}/.jenkins/plugins
  with_items:
    - "http://updates.jenkins-ci.org/latest/git.hpi"
    - "http://updates.jenkins-ci.org/latest/credentials.hpi"
    - "http://updates.jenkins-ci.org/latest/git-client.hpi"
    - "http://updates.jenkins-ci.org/latest/scm-api.hpi"
    - "http://updates.jenkins-ci.org/latest/mailer.hpi"
    - "http://updates.jenkins-ci.org/latest/matrix-project.hpi"
    - "http://updates.jenkins-ci.org/latest/job-dsl.hpi"

