    - name: create .m2
      file: path=/home/{{user_name}}/.m2 state=directory mode=0755 owner=fedora group=fedora

    - name: copy maven settings.xml
      copy: src=files/settings.xml dest=/home/{{user_name}}/.m2/settings.xml owner=fedora group=fedora
