# Installs a BPM via Red Hat internal downloads

- name: Download BPM {{bpm_version}}
  get_url: url=http://dev138.mw.lab.eng.bos.redhat.com/candidate/bpmsuite-{{bpm_version}}/jboss-bpmsuite-{{bpm_version}}-deployable-eap6.x.zip dest=~/downloads

- name: Install unzip
  sudo: true
  dnf: name=unzip state=latest

- name: Install git
  sudo: true
  dnf: name=git state=latest

- name: Extract BPM
  unarchive: src=~/downloads/jboss-bpmsuite-{{bpm_version}}-deployable-eap6.x.zip dest=~ copy=no owner=fedora group=fedora

#- name: Copy BPM specific standalone.xml
#  copy: src=files/bpm-{{ bpm_version }}-standalone.xml dest=~/jboss-eap-6.4/standalone/configuration/standalone.xml owner=fedora group=fedora
