# Installs a BPM via Red Hat internal downloads

- name: Create Download Directory
  file: path=/home/{{user_name}}/downloads state=directory mode=0755

- name: Download BPM
  get_url: url=http://download.eng.bos.redhat.com/brewroot/repos/jb-ip-6.1-build/latest/maven/org/jboss/ip/jboss-bpmsuite/{{bpm_version}}.GA-redhat-2/jboss-bpmsuite-{{bpm_version}}.GA-redhat-2-deployable-eap6.x.zip dest=/home/{{user_name}}/downloads

- name: Install unzip
  sudo: true
  dnf: name=unzip state=latest

- name: Install git
  sudo: true
  dnf: name=git state=latest

- name: Extract BPM
  unarchive: src=/home/{{user_name}}/downloads/jboss-bpmsuite-{{bpm_version}}.GA-redhat-2-deployable-eap6.x.zip dest=/home/{{user_name}}/ copy=no owner=fedora group=fedora
