# Installs a EAP 6.4 via Red Hat internal downloads

# Instructions: Manually download Red Hat Internal EAP into /files directory
# http://download.devel.redhat.com/released/JBEAP-6/6.4.3/jboss-eap-6.4.3-full-build.zip

- name: Create Download dir
  file: path=/home/{{user_name}}/downloads state=directory mode=0755

- name: Copy EAP 6.4.3
  copy: src=files/{{eap_filename}} dest=/home/{{user_name}}/downloads/{{eap_filename}} owner=fedora group=fedora

- name: Install unzip
  sudo: true
  dnf: name=unzip state=latest

- name: Extract EAP
  unarchive: src=/home/{{user_name}}/downloads/{{eap_filename}} dest=/home/{{user_name}} copy=no owner=fedora group=fedora

- name: Install JDK 1.8
  sudo: true
  dnf: name=java-1.8.0-openjdk-devel state=latest
