# Installs a workaround for https://github.com/ansible/ansible-modules-extras/issues/471
# Updates packages via DNF

- name: Install DNF Utilities
  sudo: true
  shell: dnf install yum-utils -y
  args:
    creates: /usr/bin/repomanage

- name: Update DNF Packages
  sudo: true
  dnf: name=* state=latest

- name: Install htop 
  sudo: true
  dnf: name=htop state=latest

- name: Install wget 
  sudo: true
  dnf: name=wget state=latest

- name: Install vim 
  sudo: true
  dnf: name=vim state=latest

- name: Install zip
  sudo: true
  dnf: name=zip state=latest

- name: Install JDK 1.8
  sudo: true
  dnf: name=java-1.8.0-openjdk-devel state=latest

- name: Install Git 
  sudo: true
  dnf: name=git state=latest

- name: Install Groovy
  sudo: true
  dnf: name=groovy state=latest

- name: Install Maven
  sudo: true
  dnf: name=maven state=latest

- name: Install Cowsay
  sudo: true
  dnf: name=cowsay state=latest

- name: Install Which
  sudo: true
  dnf: name=which state=latest

- name: Install pymongo
  sudo: true
  pip: name=pymongo

- name: Install request
  sudo: true
  pip: name=request

